name: Build LaTeX document
on: [push]
# Make sure the GITHUB_TOKEN has permission to upload to our releases
permissions:
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: example.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: example.pdf 
      - name: '📦 upload as latest release'
        run: |
          cd ${{github.workspace}}
          gh release delete-asset latest example.pdf
          gh release upload latest example.pdf
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash  
